# wrangler.toml ― PAGES
name = "nous-official-web"          # opcional en Pages
compatibility_date = "2023-10-01"
compatibility_flags = ["nodejs_compat"]

# carpeta que produce Astro (debe contener _worker.js y assets)
pages_build_output_dir = "./dist"

[build]
command = "pnpm build"