backend:
  name: github
  repo: nous-org/nous-official-web-v1
  branch: main
  site_domain: https://nous.cr
  base_url: https://nous.cr
  auth_endpoint: /api/auth

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { name: "title", label: "Título" }
      - { name: "date",  label: "Fecha", widget: "datetime" }
      - { name: "draft", label: "Borrador", widget: "boolean", default: false }
      - { name: "description", label: "Descripción", widget: "string" }
      - { name: "body", label: "Contenido", widget: "markdown" }

media_folder: "src/assets/images"
public_folder: "src/assets/images"