backend:
  name: github
  repo: AlessdevNous/nous-official-web-v1
  branch: main
  local_backend: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"      # <= carpeta que leerá Astro
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { name: "title", label: "Título" }
      - { name: "date",  label: "Fecha", widget: "datetime" }
      - { name: "draft", label: "Borrador", widget: "boolean", default: false }
      - { name: "description", label: "Descripción", widget: "string" }
      - { name: "body", label: "Contenido", widget: "markdown" }

media_folder: "src/assets/images" # Ubicación donde se almacenarán los archivos en el repositorio
public_folder: "src/assets/images" # El atributo src para los medios cargados